//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonfly.ToolsGui.Views.Utilities {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class OpenEvaluationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OpenEvaluationSettings defaultInstance = ((OpenEvaluationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OpenEvaluationSettings())));
        
        public static OpenEvaluationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InputFolder {
            get {
                return ((string)(this["InputFolder"]));
            }
            set {
                this["InputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoldenEvaluation {
            get {
                return ((string)(this["GoldenEvaluation"]));
            }
            set {
                this["GoldenEvaluation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NewEvaluation {
            get {
                return ((string)(this["NewEvaluation"]));
            }
            set {
                this["NewEvaluation"] = value;
            }
        }
    }
}
