//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonfly.ToolsGui.Views.Utilities {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class PgnToFenSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PgnToFenSettings defaultInstance = ((PgnToFenSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PgnToFenSettings())));
        
        public static PgnToFenSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PgnFile {
            get {
                return ((string)(this["PgnFile"]));
            }
            set {
                this["PgnFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FenFile {
            get {
                return ((string)(this["FenFile"]));
            }
            set {
                this["FenFile"] = value;
            }
        }
    }
}
