//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonfly.ToolsGui.Views.Utilities {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class TransformStockfishAnalysisSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TransformStockfishAnalysisSettings defaultInstance = ((TransformStockfishAnalysisSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TransformStockfishAnalysisSettings())));
        
        public static TransformStockfishAnalysisSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StockfishAnalysisFile {
            get {
                return ((string)(this["StockfishAnalysisFile"]));
            }
            set {
                this["StockfishAnalysisFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IntermediaryAnalysisFile {
            get {
                return ((string)(this["IntermediaryAnalysisFile"]));
            }
            set {
                this["IntermediaryAnalysisFile"] = value;
            }
        }
    }
}
